# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-09 14:49
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20150904_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributorpage',
            name='subtitle',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, default=''),
        ),
    ]
