# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-09 16:30
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_contributorpage_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributorlistpage',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='contributorlistpage',
            name='intro_text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
