# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-09 14:49
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0018_auto_20151015_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterlistpage',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='newsletterlistpage',
            name='intro_text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
