# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-01 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='is_default',
        ),
        migrations.AddField(
            model_name='themecontent',
            name='default',
            field=models.BooleanField(default=True),
        ),
    ]
