# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-02 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0002_auto_20170501_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themecontent',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
