# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-02 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0002_auto_20170501_1939'),
        ('articles', '0089_auto_20161205_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='themes.Theme'),
        ),
        migrations.AddField(
            model_name='seriespage',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='themes.Theme'),
        ),
    ]
