# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-03 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0090_auto_20170502_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='reading_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
