# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-03 18:24
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0091_articlepage_reading_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlelistpage',
            name='short_description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='serieslistpage',
            name='short_description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, default=''),
        ),
    ]
